carteiras/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('acao_buscar/', views.buscar, name='acao_buscar'),
    path('acao_list/', views.buscar, name='acao_list'),
    path('entrada_list/', views.entrada_list, name='entrada_list'),
    path('entrada_add/', views.entrada_add, name='entrada_add'),
    path('entrada_view/<int:id>/', views.entrada_view, name='entrada_view'),
    path('entrada_edit/<int:id>/', views.entrada_edit, name='entrade_edit'),
    path('entrada_delete/<int:id>/', views.entrada_delete, name='entrada_delete'),
    path('saida_list/', views.saida_list, name='saida_list'),
    path('saida_add/', views.saida_add, name='saida_add'),
    path('saida_view/<int:id>/', views.saida_view, name='saida_view'),
    path('saida_edit/<int:id>/', views.saida_edit, name='saida_edit'),
    path('saida_delete/<int:id>', views.saida_delete, name='saida_delete'),
    path('variavel_list/', views.variavel_list, name='variavel_list'),
    path('variavel_add/', views.variavel_add, name='variavel_add'),
    path('variavel_view/<int:id>/', views.variavel_view, name='variavel_view'),
    path('variavel_edit/<int:id>/', views.variavel_edit, name='variavel_edit'),
    path('variavel_delete/<int:id>/', views.variavel_delete, name='variavel_delete'),
    path('carteira/', views.carteira, name='carteira'),
    path('fixa_add/', views.fixa_add, name='fixa_add'),
    path('fixa_list/', views.fixa_list,  name='fixa_list'),
    path('fixa_view/<int:id>/', views.fixa_view, name='fixa_view'),
    path('fixa_edit/<int:id>/', views.fixa_edit, name='fixa_edit'),
    path('fixa_delete/<int:id>/', views.fixa_delete, name='fixa_delete'),
]

financeiro/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('sobre.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('carteiras/', include('carteiras.urls')),
    path('dashboard/', include('dashboard.urls')),
]
    

sobre/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home')
]

carteiras/models.py
from django.db import models
from django.contrib.auth import get_user_model

tempo_porcentagem = [
        ('DIA', 'Diario'),
        ('MES', 'Mensal'),
        ('TRI', 'Trimestral'),
        ('SEM', 'Semestral'),
        ('ANO', 'Anual'),
    ]

tipo_renda_fixa = [
    ('TED', 'Tesouro Direto'),
    ('CBD', 'CBD'),
    ('LCI', ' LCI/LCA'),
    ('DBT', 'Debêntures'),
    ('LDC', 'Letras de Câmbio'),
    ('CRI', 'CRI/CRA'),
    ('POP', 'Poupança'),
    ('OTR', 'Outro')
]
class Fixa(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.PROTECT)
    data_a = models.DateField(auto_now=True)
    valor = models.DecimalField(max_digits=11, decimal_places=2)
    rendimento = models.DecimalField(max_digits=5, decimal_places=2)
    tempo = models.CharField(max_length=3, choices=tempo_porcentagem)
    tipo = models.CharField(max_length=3, choices=tipo_renda_fixa)
    descricao_tipo = models.CharField(max_length=155)
    data_e = models.DateField(null=False, blank=False)

class Acao(models.Model):
    tks = models.CharField(max_length=10)
    nome = models.CharField(max_length=155)
    data_a = models.DateField(auto_now=True)

    def __str__(self):
        return self.nome
class Variavel(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.PROTECT)
    data_a = models.DateField(auto_now=True)
    data_e = models.DateField(null=False, blank=False)
    acao = models.ForeignKey(Acao, on_delete=models.PROTECT, blank=False, null=False)
    quantidade = models.IntegerField()
    valor = models.DecimalField(max_digits=11, decimal_places=2)

class Entrada(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.PROTECT)
    descricao = models.CharField(max_length=155, verbose_name='Descrição')
    faturado = models.BooleanField(default=False)
    valor = models.DecimalField(max_digits=11, decimal_places=2)
    data_a = models.DateField(auto_now=True)
    data_e = models.DateField(null=False, blank=False, verbose_name='Data de vencimento')
class Saida(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.PROTECT)
    descricao = models.CharField(max_length=155, verbose_name='Descrição')
    faturado = models.BooleanField(default=False)
    valor = models.DecimalField(max_digits=11, decimal_places=2)
    data_a = models.DateField(auto_now=True)
    data_e = models.DateField(null=False, blank=False, verbose_name='Data de vencimento')

carteiras/forms.py
from django import forms

from .models import Variavel, Acao, Fixa, Entrada, Saida

class AcaoForm(forms.ModelForm):
    class Meta:
        model = Acao
        fields = ('tks', 'nome')
class ContaeForm(forms.ModelForm):
    class Meta:
        model = Entrada
        fields = ('descricao', 'faturado', 'valor', 'data_e')
        widgets = {
            'data_e': forms.DateInput(
                format=('%Y-%m-%d'),
                attrs={'type': 'date'}
            ),
            'valor': forms.NumberInput(
                attrs={'step': 0.01}
            )
        }
class ContasForm(forms.ModelForm):
    class Meta:
        model = Saida
        fields = ('descricao', 'faturado', 'valor', 'data_e')
        widgets = {
            'data_e': forms.DateInput(
                format=('%Y-%m-%d'),
                attrs={'type': 'date'}
            ),
            'valor': forms.NumberInput(
                attrs={'step': 0.01}
            )
        }

class VariavelForm(forms.ModelForm):
    class Meta:
        model = Variavel
        fields = ('acao', 'data_e', 'quantidade', 'valor')
        widgets = {
            'data_e': forms.DateInput(
                format=('%Y-%m-%d'),
                attrs={'type': 'date'}
            ),
            'valor': forms.NumberInput(
                attrs={'step': 0.01}
            )
        }
        
class FixaForm(forms.ModelForm):
    class Meta:
        model = Fixa
        fields = ('valor', 'rendimento', 'tempo', 'data_e', 'tipo', 'descricao_tipo')
        widgets = {
            'valor': forms.NumberInput(
                attrs={'step': 0.01}
            ),
            'data_e': forms.DateInput(
                format=('%Y-%m-%d'),
                attrs={'type': 'date'}
            )
        }

carteiras/views.py
from django.http import HttpResponse
from django.shortcuts import redirect, render, get_object_or_404
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.contrib import messages

import yfinance as yf
#import investpy as inv

from .forms import VariavelForm, FixaForm, ContaeForm, ContasForm
from .models import Acao, Variavel, Fixa, Entrada, Saida

import json
import pandas as pd

class Busca:


    def __int__(self, codigo):
        self.codigo = codigo
    def acao(self):
        cod = self.codigo
        res = yf.Ticker(cod)
        historico = res.history(period='2d')
        historico = historico.reset_index()
        historico.columns = ['date', 'open', 'high', 'low', 'close', 'volume',
                             'dividends', 'stock']
        historico['date'] = pd.to_datetime(historico['date'], errors='coerce')
        historico['date'] = historico['date'].dt.strftime('%m-%d-%Y')
        dts = historico.reset_index().to_json(orient='records', date_format='iso')
        cpt = [{'nome': res.info['longName'], 'tks': self.codigo.upper()}]
        cpp = json.dumps(cpt)
        cpp = json.loads(cpp)
        data = []
        data = json.loads(dts)
        return data, cpp
    #CPLE3.SA
@login_required
def buscar(request):
    search = request.GET.get('search')
    if search:
        tick = Busca()
        bs = search
        tick.codigo = bs.upper() + ".SA"
        res = tick.acao()
        acao = res[0]
        cpt = res[1]
        context = {
            'acao': acao,
            'cpt': cpt,
        }
        if request.POST:
            nome_a = res[1][0]['nome']
            tick_a = res[1][0]['tks']
            acao = Acao(tks=tick_a, nome=nome_a)
            acao.save()
            return redirect('variavel_add')

        return render(request, 'carteiras/acao_list.html', context)
    else:
        return render(request, 'carteiras/acao_buscar.html')
@login_required
def carteira(request):
    return render(request, 'carteiras/carteira.html')
@login_required
def entrada_add(request):
    if request.method == 'POST':
        form = ContaeForm(request.POST or None)
        if form.is_valid():
            entrada = form.save(commit=False)
            entrada.user = request.user
            entrada.save()
            return redirect('carteira')
    else:
        form = ContaeForm()
        return render(request, 'carteiras/entrada_add.html', {'form': form})
@login_required
def entrada_list(request):
    lista_v = Entrada.objects.all().order_by('-data_a').filter(user=request.user)
    paginator = Paginator(lista_v, 10)
    page = request.GET.get('page')
    lista = paginator.get_page(page)
    return render(request, 'carteiras/entrada_list.html', {'lista': lista})
@login_required
def entrada_view(request, id):
    entrada = get_object_or_404(Entrada, pk=id)
    return render(request, 'carteiras/entrada_view.html', {'entrada': entrada})
@login_required
def entrada_edit(request, id):
    entrada = get_object_or_404(Entrada, pk=id)
    form = ContaeForm(instance=entrada)
    if(request.method == 'POST'):
        form = ContaeForm(request.POST, instance=entrada)
        if(form.is_valid()):
            entrada.save()
            return redirect('carteira')
        else:
            return render(request, 'carteiras/entrada_edit.html',
                          {'form': form, 'entrada': entrada})
    else:
        return render(request, 'carteiras/entrada_edit.html',
                      {'form': form, 'entrada': entrada})
@login_required
def entrada_delete(request, id):
    entrada = get_object_or_404(Entrada, pk=id)
    entrada.delete()
    messages.info(request, 'Deletado com sucesso!')
    return redirect('carteira')
@login_required
def saida_add(request):
    if request.method == 'POST':
        form = ContasForm(request.POST or None)
        if form.is_valid():
            saida = form.save(commit=False)
            saida.user = request.user
            saida.save()
            return redirect('carteira')
    else:
        form = ContasForm()
        return render(request, 'carteiras/saida_add.html', {'form': form})
@login_required
def saida_list(request):
    lista_v = Saida.objects.all().order_by('-data_a').filter(user=request.user)
    paginator = Paginator(lista_v, 10)
    page = request.GET.get('page')
    lista = paginator.get_page(page)
    return render(request, 'carteiras/saida_list.html', {'lista': lista})
@login_required
def saida_view(request, id):
    saida = get_object_or_404(Saida, pk=id)
    return render(request, 'carteiras/saida_view.html', {'saida': saida})
@login_required
def saida_edit(request, id):
    saida = get_object_or_404(Saida, pk=id)
    form = ContasForm(instance=saida)
    if(request.method == 'POST'):
        form = ContasForm(request.POST, instance=saida)
        if(form.is_valid()):
            saida.save()
            return redirect('carteira')
        else:
            return render(request, 'carteiras/saida_edit.html',
                          {'form': form, 'saida': saida})
    else:
        return render(request, 'carteiras/saida_edit.html',
                      {'form': form, 'saida': saida})
@login_required
def saida_delete(request, id):
    saida = get_object_or_404(Saida, pk=id)
    saida.delete()
    messages.info(request, 'Deletado com sucesso!')
    return redirect('carteira')
@login_required
def variavel_add(request):
    if request.method == 'POST':
        form = VariavelForm(request.POST or None)
        if form.is_valid():
            variavel = form.save(commit=False)
            variavel.user = request.user
            variavel.save()
            return redirect('carteira')
    else:
        form = VariavelForm()
        return render(request, 'carteiras/variavel_add.html', {'form': form})
@login_required
def variavel_list(request):
    lista_v = Variavel.objects.all().order_by('-data_a').filter(user=request.user)
    paginator = Paginator(lista_v, 10)
    page = request.GET.get('page')
    lista = paginator.get_page(page)
    return render(request, 'carteiras/variavel_list.html', {'lista': lista})
@login_required
def variavel_view(request, id):
    variavel = get_object_or_404(Variavel, pk=id)
    return render(request, 'carteiras/variavel_view.html',
                  {'variavel': variavel})
@login_required
def variavel_edit(request, id):
    variavel = get_object_or_404(Variavel, pk=id)
    form = VariavelForm(instance=variavel)

    if(request.method == 'POST'):
        form = VariavelForm(request.POST, instance=variavel)
        if(form.is_valid()):
            variavel.save()
            return redirect('carteira')
        else:
            return render(request, 'carteiras/variavel_edit.html',
                          {'form': form, 'variavel': variavel})
    else:
        return render(request, 'carteiras/variavel_edit.html',
                      {'form': form, 'variavel': variavel})
@login_required
def variavel_delete(request, id):
    variavel = get_object_or_404(Variavel, pk=id)
    variavel.delete()
    messages.info(request, 'Investimento deletado com sucesso!')
    return redirect('carteira')
@login_required
def fixa_add(request):
    if request.method == 'POST':
        form = FixaForm(request.POST or None)

        if form.is_valid():
            fixa = form.save(commit=False)
            fixa.user = request.user
            fixa.save()
            return redirect('carteira')
    else:
        form = FixaForm()
        return render(request, 'carteiras/fixa_add.html', {'form': form})
@login_required
def fixa_list(request):
    lista_f = Fixa.objects.all().order_by('-data_a').filter(user=request.user)
    paginator = Paginator(lista_f, 10)
    page = request.GET.get('page')
    lista = paginator.get_page(page)
    return render(request, 'carteiras/fixa_list.html', {'lista': lista})
@login_required
def fixa_view(request, id):
    fixa = get_object_or_404(Fixa, pk=id)
    return render (request, 'carteiras/fixa_view.html', {'fixa': fixa})
@login_required
def fixa_edit(request, id):
    fixa = get_object_or_404(Fixa, pk=id)
    form = FixaForm(instance=fixa)

    if(request.method == 'POST'):
        form = FixaForm(request.POST, instance=fixa)
        if(form.is_valid()):
            fixa.save()
            return redirect('carteira')
        else:
            return render(request, 'carteiras/fixa_edit.html',
                          {'form': form, 'fixa': fixa})
    else:
        return render(request, 'carteiras/fixa_edit.html',
                      {'form': form, 'fixa': fixa})
@login_required
def fixa_delete(request, id):
    fixa = get_object_or_404(Fixa, pk=id)
    fixa.delete()
    messages.info(request, 'Investimento deletado com sucesso!')
    return redirect('carteira')

carteiras/templates/carteiras/acao_buscar.html
{% extends 'index.html' %}

{% block title %} Teste {% endblock %}
{% block search %}
  <form class="d-flex">
        <input class="form-control me-2" type="text" id="search" name="search" placeholder="Digite o ticker para buscar..." value="{{ request.GET.search }}">
        <button class="btn btn-outline-success" type="submit">Search</button>
  </form>
{% endblock %}
{% block content %}

{% endblock %}

carteiras/templates/carteiras/acao_list.html
{% extends 'index.html' %}

{% block title %}Lista de ações{% endblock %}

{% block search %}
<form class="d-flex">
    <input class="form-control me-2" type="text" id="search" name="search" placeholder="Digite o ticker para buscar..." value="{{ request.GET.search }}">
    <button class="btn btn-outline-success" type="submit">Search</button>
</form>
{% endblock %}

{% block content %}
    <div class="container">
      <h2 class="text-center"><u>Tabela de Investimentos</u></h2><br>
      <div class="dados_acao">
      {% for c in cpt %}
        <form method="post">
          {% csrf_token %}
          <h2>{{c.nome}}</h2>
          <h3>{{c.tks}}</h3>
          <input type="submit" class="btn btn-success" value="Criar ação">
        </form>
      {% endfor %}
      </div>
      <table class="table table-dark table-striped">
        <thead>
          <tr>
            <th>Data</th>
            <th>Abertura</th>
            <th>Maxima</th>
            <th>Minima</th>
            <th>Fechamento</th>
            <th>Volume</th>
            <th>Dividendos</th>
            <th>Stock Splits</th>
          </tr>
        </thead>
        <tbody>
        {% if acao %}
        {% for a in acao %}

          <tr>
            <td>{{a.date}}</td>
            <td>{{a.open}}</td>
            <td>{{a.high}}</td>
            <td>{{a.low}}</td>
            <td>{{a.close}}</td>
            <td>{{a.volume}}</td>
            <td>{{a.dividends}}</td>
            <td>{{a.stock}}</td>
          </tr>

        {% endfor %}
        {% endif %}
        </tbody>
      </table>
    </div>
{% endblock %}

carteiras/templates/carteiras/acao_view.html
{% extends 'index.html' %}

{% block title %} Ações {% endblock %}

{% block content %}
<div class="search-div">
    <input class="form-control" type="text" id="search" name="search" placeholder="Digite o nome da OS para buscar">
    <spam><i class="fas fa-search"></i></spam>
</div>
<ul class="variavel-list">
    {% for acao in carteiras %}
    <li class="variavel-item">
        <spam><a class="lista-titulo" href="/carteiras/acao_view{{acao}}">{{acao.Código}}</a></spam>
        <a href="/carteiras/variavel_delete/{{variavel.id}}" class="delete-btn" onclick="return confirm('Realmente deseja excluir?')"><spam><i class="fas fa-trash"></i></spam></a>
        <a href="/carteiras/variavel_edit/{{variavel.id}}"><spam><i class="fas fa-edit"></i></spam></a>
    </li>
    {% endfor %}
</ul>
{% endblock %}

carteiras/templates/carteiras/carteira.html
{% extends 'index.html' %}

{% block title %}Carteiras{% endblock %}
{% block search %}
<form class="d-flex">
    <input class="form-control me-2" type="text" id="search" name="search" placeholder="Digite o ticker para buscar..." value="{{ request.GET.search }}">
    <button class="btn btn-outline-success" type="submit">Search</button>
</form>
{% endblock %}

{% block content %}
<div class="carteira">
    <h2>Minha Carteira de Investimentos</h2>
    <div class="carteira_investimento">
    <div class="renda_fixa">
        <h3><a href="{% url 'fixa_list' %}">Investimentos de renda fixa</a></h3>
    </div>
    <div class="renda_variavel">
        <h3><a href="{% url 'variavel_list' %}">Investimentos de renda variavel</a></h3>
    </div>
    </div>
</div>

{% endblock %}

carteiras/templates/carteiras/entrada_add.html
{% extends 'index.html' %}

{% block title %}Entrada{% endblock %}

{% block content %}
<div class="offset-3 col-6 form-div">
    <h1>Adicione</h1>
    <form class="form-add" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" class="btn btn-success" value="Adicionar">
    </form>
</div>

{% endblock %}

carteiras/templates/carteiras/entrada_view.html
{% extends 'index.html' %}

{% block title %}Pagamentos recebidos{% endblock %}

{% block content %}
<div class="view_body">
    <div class="investimento_detalhe">
        <h1>Detalhes do Pagamento</h1>
        <h3>Descrição</h3>
        <h5>{{entrada.descricao}}</h5>
        <h3>Valor recebido</h3>
        <h5>{{entrada.valor}}</h5>
        <h3>Confirmação de recebimento</h3>
        <h5>{{entrada.faturado}}</h5>
        <h3>Data do recebimento</h3>
        <h5>{{entrada.data_e}}</h5>
    </div>
    <div class="btn_edit_delete">
        <div class="btn-group" role="group" aria-label="Basic mixed styles example" style="margin-left: 5em;">
        <a href="/carteiras/entrada_delete/{{entrada.id}}" onclick="return confirm('Realmente deseja excluir?')"><button type="button" class="btn btn-danger">Deletar</button></a>
        <a href="/carteiras/entrada_edit/{{entrada.id}}"><button type="button" class="btn btn-warning">Editar</button></a>
        <a href="{% url 'entrada_add' %}"><button type="button" class="btn btn-success">Adicionar</button></a>
    </div>
    </div>
</div>
{% endblock %}

carteiras/templates/carteiras/fixa_edit.html
{% extends 'index.html' %}

{% block title %}Editando{% endblock %}

{% block content %}
<div class="offset-3 col-6 form-div">
    <h1>Editando {{fixa.descricao_tipo}}</h1>
    <form action="{% url 'fixa_edit' fixa.id %}" class="form-add" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        {{data_e|date:'%d-%m-%Y'}}

        <input type="submit" class="btn btn-success" value="Editar Ordem">
    </form>
</div>


{% endblock %}

carteiras/templates/carteiras/fixa_list.html
{% extends 'index.html' %}
{% block title %}Lista de renda fixa{% endblock %}

{% block content %}
<div class="carteira_h1">
<h1>Investimentos em renda Fixa</h1>
<a href="{% url 'fixa_add' %}"><button type="button" class="btn btn-outline-success">Adicionar</button></a>
</div>
  <ul class="carteira_list">
        {% for fixa in lista %}
            <a href="/carteiras/fixa_view/{{fixa.id}}">
            <li>
                <div class="carteira_detalhe">
                <h3>Descrição</h3>
               <h5 class="carteira_detalhe_h5" >{{fixa.descricao_tipo}}</h5>
                </div>
                <div class="carteira_detalhe">
                <h3>Tipo de investimento</h3>
                <h5 class="carteira_detalhe_h5" >{{fixa.get_tipo_display}}</h5>
                </div>
                <div class="carteira_detalhe">
                <h3>Valor Investido</h3>
                <h5 class="carteira_detalhe_h5">{{fixa.valor}}</h5>
                </div>
            </li>
            </a>
        {% endfor %}
  </ul>
{% endblock %}

carteiras/templates/carteiras/fixa_view.html
{% extends 'index.html' %}

{% block title %}Investimento renda Fixa{% endblock %}

{% block content %}
<div class="view_body">
    <div class="investimento_detalhe">
        <h1>Detalhes do Investimento</h1>
        <h3>Descrição</h3>
        <h5>{{fixa.descricao_tipo}}</h5>
        <h3>Valor investido</h3>
        <h5>{{fixa.valor}}</h5>
        <h3>Tipo de investimento</h3>
        <h5>{{fixa.get_tipo_display}}</h5>
        <h3>Data do investimento</h3>
        <h5>{{fixa.data_e}}</h5>
        <h3>Porcentagem de rendimento</h3>
        <h5>{{fixa.rendimento}}</h5>
        <h3>Frequência de pagamento do rendimento</h3>
        <h5>{{fixa.get_tempo_display}}</h5>
    </div>
    <div class="btn_edit_delete">
        <div class="btn-group" role="group" aria-label="Basic mixed styles example" style="margin-left: 5em;">
        <a href="/carteiras/fixa_delete/{{fixa.id}}" onclick="return confirm('Realmente deseja excluir?')"><button type="button" class="btn btn-danger">Deletar</button></a>
        <a href="/carteiras/fixa_edit/{{fixa.id}}"><button type="button" class="btn btn-warning">Editar</button></a>
        <a href="{% url 'fixa_add' %}"><button type="button" class="btn btn-success">Adicionar</button></a>
    </div>
    </div>
</div>
{% endblock %}

carteiras/templates/carteiras/saida_add.html
{% extends 'index.html' %}

{% block title %}Saida{% endblock %}

{% block content %}
<div class="offset-3 col-6 form-div">
    <h1>Adicione</h1>
    <form class="form-add" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" class="btn btn-success" value="Adicionar">
    </form>
</div>

{% endblock %}

carteiras/templates/carteiras/saida_list.html
{% extends 'index.html' %}
{% block title %}Lista de contas{% endblock %}

{% block content %}
<div class="carteira_h1">
<h1>Lista de contas</h1>
<a href="{% url 'saida_add' %}"><button type="button" class="btn btn-outline-success">Adicionar</button></a>
</div>
  <ul class="carteira_list">
        {% for saida in lista %}
            <a href="/carteiras/saida_view/{{saida.id}}">
            <li>
                <div class="carteira_detalhe">
                <h3>Descrição</h3>
               <h5 class="carteira_detalhe_h5" >{{saida.descricao}}</h5>
                </div>
                <div class="carteira_detalhe">
                <h3>Valor da conta</h3>
                <h5 class="carteira_detalhe_h5" >{{saida.valor}}</h5>
                </div>
                <div class="carteira_detalhe">
                <h3>Data de vencimento</h3>
                <h5 class="carteira_detalhe_h5">{{saida.data_e}}</h5>
                </div>
            </li>
            </a>
        {% endfor %}
  </ul>
{% endblock %}

carteiras/templates/carteiras/saida_view.html
{% extends 'index.html' %}

{% block title %}Pagamentos recebidos{% endblock %}

{% block content %}
<div class="view_body">
    <div class="investimento_detalhe">
        <h1>Detalhes da conta</h1>
        <h3>Descrição</h3>
        <h5>{{saida.descricao}}</h5>
        <h3>Valor recebido</h3>
        <h5>{{saida.valor}}</h5>
        <h3>Confirmação de recebimento</h3>
        <h5>{{saida.faturado}}</h5>
        <h3>Data do recebimento</h3>
        <h5>{{saida.data_e}}</h5>
    </div>
    <div class="btn_edit_delete">
        <div class="btn-group" role="group" aria-label="Basic mixed styles example" style="margin-left: 5em;">
        <a href="/carteiras/saida_delete/{{saida.id}}" onclick="return confirm('Realmente deseja excluir?')"><button type="button" class="btn btn-danger">Deletar</button></a>
        <a href="/carteiras/saida_edit/{{saida.id}}"><button type="button" class="btn btn-warning">Editar</button></a>
        <a href="{% url 'saida_add' %}"><button type="button" class="btn btn-success">Adicionar</button></a>
    </div>
    </div>
</div>
{% endblock %}

carteiras/templates/carteiras/variavel_add.html
{% extends 'index.html' %}

{% block title %}Variavel{% endblock %}

{% block content %}
<div class="offset-3 col-6 form-div">
    <h1>Adicione uma nova ação</h1>
    <form class="form-add" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" class="btn btn-success" value="Criar ação">
    </form>
</div>

{% endblock %}

carteiras/templates/carteiras/variavel_view.html
{% extends 'index.html' %}

{% block title %}Adicionar{% endblock %}

{% block content %}
<div class="view_body">
    <div class="investimento_detalhe">
        <h1>Detalhes do Investimento</h1>
        <h3>Descrição</h3>
        <h5>{{variavel.acao}}</h5>
        <h3>Valor pago por ação</h3>
        <h5>{{variavel.valor}}</h5>
        <h3>Quantidade</h3>
        <h5>{{variavel.quantidade}}</h5>
        <h3>Data do investimento</h3>
        <h5>{{variavel.data_e}}</h5>
    </div>
    <div class="btn_edit_delete">
        <div class="btn-group" role="group" aria-label="Basic mixed styles example" style="margin-left: 5em;">
        <a href="/carteiras/variavel_delete/{{variavel.id}}" onclick="return confirm('Realmente deseja excluir?')"><button type="button" class="btn btn-danger">Deletar</button></a>
        <a href="/carteiras/variavel_edit/{{variavel.id}}"><button type="button" class="btn btn-warning">Editar</button></a>
        <a href="{% url 'variavel_add' %}"><button type="button" class="btn btn-success">Adicionar</button></a>
    </div>
    </div>
</div>
{% endblock %}